# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hutter.io
author:
  name: Manuel Hutter
  twitter: dratir
  github: mhutter
email: manuel at hutter.io
description: > # this means to ignore newlines until "baseurl:"
  Webdev, DevOps, Linux and the likes...
  I'm a Linux System Engineer that likes to pretend he's a web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hutter.io" # the base hostname & protocol for your site

twitter:
  username: dratir

# Build settings
permalink: pretty
paginate: 10

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-crosspost-to-medium

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - README.md
include:
  - '.htaccess'

jekyll-crosspost_to_medium:
  enabled: true
  cache: .jekyll-crosspost_to_medium
  status: public
  license: all-rights-reserved
  text: '<p><i>(first published on <a href="{{ url }}">hutter.io</a>)</i></p>'
  backdate: true
