# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: hutter.io
email: manuel@hutter.io
description: > # this means to ignore newlines until "baseurl:"
  Webdev, Linux and the likes...
  I'm a Linux System Engineer that likes to pretend he's a web developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hutter.io" # the base hostname & protocol for your site
twitter_username: dratir
github_username:  mhutter

# Build settings
markdown: kramdown
highlight: rouge
permalink: pretty

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.locl
  - Rakefile
  - vendor
include:
  - '.htaccess'
