title: Manuel Hutter
author: Manuel Hutter
# email: manuel@hutter.io
description: Manuel Hutter. Webdev, Linux, and the likes...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mhutter.net"

permalink: pretty
paginate: 10

sass:
  style: :compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
include:
  - .htaccess

# Build settings
markdown: kramdown
