title: Manuel Hutter
# email: manuel@hutter.io
# description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mhutter.net"
twitter_username: mhutter
github_username:  mhutter

paginate: 10

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile

# Build settings
markdown: kramdown
