---
version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5
    environment:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: 'true'
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Build site
          command: rake rebuild
      - run:
          name: Check site
          command: bundle exec htmlproofer ./_site --disable-external

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - persist_to_workspace:
          root: ~/repo
          paths: _site

  deploy:
    docker:
      - image: ubuntu
    working_directory: ~/repo
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update -q && \
            apt-get install rsync ca-certificates -yq
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure SSH
          command: |
            mkdir -p ~/.ssh && \
            echo "User $SSH_USER" >> ~/.ssh/config
      - run:
          name: Deploy site
          command: |
            rsync -aPz --delete _site/ hutter.io:public_html/hutter.io/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
